### ISSUE TITLE
Color decaration

### ISSUE THREAD

**Issue by exdeniz** [d4rkr00t/language-stylus#48]
I have bug in developer console.
```
Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at vscode_1.window.onDidChangeActiveTextEditor.editor (/Users/exdeniz/.vscode/extensions/sysoev.language-stylus-1.7.2/out/src/color-decorators.js:103:20)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:30930)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:34737)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:346482
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:30930)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:34737)
    at t.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:300894)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:266424)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:154927)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:155604)
```

**Comment by d4rkr00t** [comment]
Wow, thanks, i'll take a look. What version of Code do you use?

**Comment by exdeniz** [comment]
Version 1.12.2 (1.12.2) Latest

**Comment by melrefaie** [comment]
Me too 

Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at vscode_1.window.onDidChangeActiveTextEditor.editor (C:\Users\Mohamed Maher\.vscode\extensions\sysoev.language-stylus-1.7.2\out\src\color-decorators.js:103:20)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:30934)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:34741)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:346486
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:30934)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:34741)
    at t.$acceptDocumentsAndEditorsDelta (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:300898)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:266428)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:154931)
    at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:155608)
e.onUnexpectedError @ shell.ts:474

![screenshot_1](https://cloud.githubusercontent.com/assets/25461028/26151134/b21a084c-3b01-11e7-8c7e-ec5920447636.png)

Vs code version 1.12.2
